language: node_js
node_js:
  - 9
  - 8
  - 7
  - 6
after_script:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.12.0
services: mongodb
cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
